---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/Speech
    about: Read the documentation for Speech
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/Speech/discussions
    about: Ask questions and discuss with the community
