using CommunityToolkit.Mvvm.Input;
using DemaConsulting.Speech.Demo.ModelCatalogSubsystem;
using DemaConsulting.Speech.Demo.Tests.Fakes;
using DemaConsulting.Speech.ModelManagementSubsystem;
using NSubstitute;

namespace DemaConsulting.Speech.Demo.Tests.Ots;

/// <summary>
///     Integration tests for the CommunityToolkit.Mvvm OTS software item.
/// </summary>
/// <remarks>
///     The demo depends on this package's source generators for its change notification and
///     command plumbing, so these tests verify that the generated members genuinely exist and
///     behave, rather than assuming a source generator ran.
/// </remarks>
public class CommunityToolkitMvvmTests
{
    /// <summary>
    ///     Proves that the package's <c>ObservableProperty</c> generator produces a public property
    ///     that raises change notification, which is what keeps every bound demo panel current.
    /// </summary>
    [Fact]
    public void CommunityToolkitMvvm_ObservableProperty_Assigned_RaisesPropertyChanged()
    {
        // Arrange: a ViewModel whose observable state is generated by the package
        var row = new ModelListItemViewModel(FakeSpeechModel.Descriptor("model-a"));
        var changed = new List<string?>();
        row.PropertyChanged += (_, args) => changed.Add(args.PropertyName);

        // Act: assign through the generated property
        row.State = SpeechModelState.Downloaded;

        // Assert: the generated setter stored the value and announced the change
        Assert.Equal(SpeechModelState.Downloaded, row.State);
        Assert.Contains(nameof(ModelListItemViewModel.State), changed);
    }

    /// <summary>
    ///     Proves that the package's <c>RelayCommand</c> generator produces a bindable command that
    ///     invokes the annotated method, which is what lets the demo's buttons stay code-behind
    ///     free.
    /// </summary>
    [Fact]
    public void CommunityToolkitMvvm_RelayCommand_Executed_InvokesAnnotatedMethod()
    {
        // Arrange: a ViewModel with a generated synchronous command
        var service = Substitute.For<IModelCatalogService>();
        service.Enumerate().Returns([]);
        var viewModel = new ModelCatalogViewModel(service);

        // Act: execute the generated command the way a bound button does
        viewModel.RefreshCommand.Execute(null);

        // Assert: the annotated method ran (once at construction, once through the command)
        Assert.True(viewModel.RefreshCommand.CanExecute(null));
        service.Received(2).Enumerate();
    }

    /// <summary>
    ///     Proves that the package's <c>RelayCommand</c> generator produces a cancellable async
    ///     command for an asynchronous method, which is what lets the demo run a model download
    ///     without blocking the UI thread.
    /// </summary>
    [Fact]
    public async Task CommunityToolkitMvvm_AsyncRelayCommand_Executed_AwaitsAnnotatedMethod()
    {
        // Arrange: a ViewModel with a generated asynchronous command over one downloadable model
        var service = Substitute.For<IModelCatalogService>();
        service.Enumerate().Returns([FakeSpeechModel.Descriptor("model-a")]);
        service
            .DownloadAsync("model-a", Arg.Any<IProgress<SpeechModelDownloadProgress>>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromResult(new SpeechModelDownloadResult(SpeechModelDownloadOutcome.Installed)));
        var viewModel = new ModelCatalogViewModel(service);

        // Act: execute the generated async command and await its completion
        var command = Assert.IsAssignableFrom<IAsyncRelayCommand>(viewModel.DownloadCommand);
        await command.ExecuteAsync(viewModel.Models[0]);

        // Assert: the awaited method completed and updated the row
        Assert.Equal(SpeechModelState.Downloaded, viewModel.Models[0].State);
    }
}
