namespace DemaConsulting.Speech.SynthesisSubsystem;

/// <summary>
///     Internal, mockable seam over one loaded offline text-to-speech engine: synthesizes one
///     segment of text at a time into raw audio.
/// </summary>
/// <remarks>
///     This seam exists for the same reason as <see cref="RecognitionSubsystem.IRecognitionEngine"/>
///     (Phase 3): it confines every sherpa-onnx TTS interop call to a single implementation
///     (<see cref="SherpaOnnxSynthesisEngine"/>) so <see cref="SherpaOnnxSpeechSynthesizer"/>'s
///     chunking, pipelining, and playback logic is fully unit-testable with a pure managed fake.
///     No native sherpa-onnx runtime binary and no downloaded model are ever required to run the
///     synthesis subsystem's tests.
///     <para>
///     Implementations are not thread-safe with respect to concurrent calls, but
///     <see cref="Generate"/> may be called from a background producer thread while a caller
///     concurrently disposes the engine from another thread to stop an in-flight session; see
///     <see cref="SherpaOnnxSpeechSynthesizer"/> for how that race is contained.
///     </para>
/// </remarks>
internal interface ISynthesisEngine : IDisposable
{
    /// <summary>
    ///     Gets the sample rate, in Hz, of the audio <see cref="Generate"/> produces.
    /// </summary>
    /// <remarks>
    ///     Unlike a streaming recognition model, an offline TTS model does not pre-declare its
    ///     output rate ahead of loading; this is read from the loaded native engine itself once
    ///     construction has completed. Reading this property never throws.
    /// </remarks>
    int SampleRate { get; }

    /// <summary>
    ///     Synthesizes one segment of text into audio.
    /// </summary>
    /// <param name="text">
    ///     The text to synthesize. May be empty; an empty segment is never generated by
    ///     <see cref="SherpaOnnxSpeechSynthesizer"/>, which handles pure-silence segments without
    ///     calling this method at all, but implementations must still behave predictably if given
    ///     one.
    /// </param>
    /// <param name="speed">
    ///     The speaking-rate multiplier for this call, where <c>1.0</c> is the model's normal
    ///     rate. Must be greater than zero.
    /// </param>
    /// <param name="speakerId">The speaker/voice id to use, for a multi-speaker model.</param>
    /// <returns>The synthesized audio for the segment.</returns>
    /// <exception cref="ObjectDisposedException">Thrown when the engine has been disposed.</exception>
    /// <remarks>
    ///     This is a blocking, synchronous, whole-segment call: it returns only once the segment
    ///     has been fully synthesized. Callers wishing to overlap synthesis with playback must run
    ///     it on a background thread, which <see cref="SherpaOnnxSpeechSynthesizer"/> does.
    /// </remarks>
    EngineAudio Generate(string text, float speed, int speakerId);
}
