namespace DemaConsulting.Speech.SynthesisSubsystem;

/// <summary>
///     Mockable, engine-neutral seam over one loaded offline text-to-speech engine: synthesizes
///     one segment of text at a time into raw audio.
/// </summary>
/// <remarks>
///     This seam exists for the same reason as <c>RecognitionSubsystem.IRecognitionBackend</c>: it
///     confines every native TTS interop call behind a seam that names no inference-engine type,
///     so <see cref="SynthesisSession"/>'s chunking, pipelining, and playback logic is fully
///     unit-testable with a pure managed fake. No native sherpa-onnx runtime binary and no
///     downloaded model are ever required to run the synthesis subsystem's tests. This seam is
///     public, mirroring <see cref="ModelManagementSubsystem.ISynthesisModel.CreateBackend(string)"/>'s
///     public visibility: a third-party synthesis model implementing
///     <see cref="ModelManagementSubsystem.ISynthesisModel"/> must be able to implement this
///     interface to return its own loaded backend from <c>CreateBackend</c>, without needing any
///     special assembly access. The sibling <c>DemaConsulting.Speech.Sherpa</c> package's
///     <c>SherpaOnnxSynthesisEngine</c> is simply this library's own built-in implementation.
///     <para>
///     Renamed from <c>ISynthesisEngine</c> so the "engine" vocabulary is reserved for the public
///     Layer 3 <see cref="ISpeechSynthesizerEngine"/> contract, removing the naming collision
///     between the public, loaded-model-level type and this per-segment native seam.
///     </para>
///     <para>
///     Implementations are not thread-safe with respect to concurrent calls, but
///     <see cref="Generate"/> may be called from a background worker thread while a caller
///     concurrently disposes the engine from another thread to stop an in-flight session; see
///     <see cref="SynthesisSession"/> for how that race is contained.
///     </para>
/// </remarks>
public interface ISynthesisBackend : IDisposable
{
    /// <summary>
    ///     Gets the sample rate, in Hz, of the audio <see cref="Generate"/> produces.
    /// </summary>
    /// <remarks>
    ///     Unlike a streaming recognition model, an offline TTS model does not pre-declare its
    ///     output rate ahead of loading; this is read from the loaded native engine itself once
    ///     construction has completed. Reading this property never throws.
    /// </remarks>
    int SampleRate { get; }

    /// <summary>
    ///     Synthesizes one segment of text into audio.
    /// </summary>
    /// <param name="text">
    ///     The text to synthesize. May be empty; an empty segment is never generated by
    ///     <see cref="SynthesisSession"/>, which handles pure-silence segments without
    ///     calling this method at all, but implementations must still behave predictably if given
    ///     one.
    /// </param>
    /// <param name="speed">
    ///     The speaking-rate multiplier for this call, where <c>1.0</c> is the model's normal
    ///     rate. Must be greater than zero.
    /// </param>
    /// <param name="speakerId">The speaker/voice id to use, for a multi-speaker model.</param>
    /// <returns>The synthesized audio for the segment.</returns>
    /// <exception cref="ObjectDisposedException">Thrown when the engine has been disposed.</exception>
    /// <remarks>
    ///     This is a blocking, synchronous, whole-segment call: it returns only once the segment
    ///     has been fully synthesized. Callers wishing to overlap synthesis with playback, or to
    ///     bound how long they wait for this call, must run it on a background thread with its own
    ///     cooperative-cancel-then-abandon policy, which <see cref="SynthesisSession"/>
    ///     does via <see cref="DedicatedWorker"/>.
    /// </remarks>
    EngineAudio Generate(string text, float speed, int speakerId);
}
